version: '3.8'
services:
    backend:
        build: ./backend
        container_name: qwen_qwen3_8b_app11_backend_5581
        ports:
            - "5581:5581"
        restart: always
        environment:
            - PYTHONUNBUFFERED=1 

    frontend:
        build: ./frontend
        container_name: qwen_qwen3_8b_app11_frontend_8581
        ports:
            - "8581:8581"
        environment:
            - PORT=8581
            - VITE_BACKEND_API_TARGET=http://backend:5581
            - VITE_FRONTEND_PORT=8581
        restart: always
        depends_on:
            - backend
